
def load():
    print ("[*] Generating...")
    os.system("clear")
    print ("1%")
    time.sleep(1.9)
    os.system("clear")
    print ("15%")
    time.sleep(1.9)
    os.system("clear")
    print ("30%")
    time.sleep(1.9)
    os.system("clear")
    print ("50%")
    time.sleep(1.9)
    os.system("clear")
    print ("100%")
    time.sleep(3)
